[package]
name = "website"
version = "0.1.0"
authors = ["zTgx"]

[dependencies]
hyper = { path = "../audit_hyper" }
tera = { path = "../tera" } 
lazy_static = "1.3.0"
serde_json = "1.0"
url = "1.0"
futures = "0.1.21"

